# Generated by Django 4.1.3 on 2022-11-22 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasbet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('prize', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the related user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('commance_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('scores', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('multiplier', models.FloatField()),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasbet.bookmaker', verbose_name='the related bookmaker')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasbet.market', verbose_name='the related market')),
            ],
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasbet.game', verbose_name='the related game'),
        ),
        migrations.CreateModel(
            name='BetOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasbet.bet', verbose_name='the related bet')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasbet.outcome', verbose_name='the related outcome')),
            ],
        ),
    ]
