# Generated by Django 4.1.3 on 2022-11-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasbet', '0002_bet_bookmaker_game_market_outcome_bookmaker_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='commance_time',
            new_name='commence_time',
        ),
    ]
